sealed case class Base (
  astatine: Option[Astatine] = None,
  hydrogen: Option[Hydrogen] = None,
  fluorine: Option[Fluorine] = None,
  iodine: Option[Iodine] = None,
  chlorine: Option[Chlorine] = None,
  agricium: Option[Agricium] = None,
  gold: Option[Gold] = None,
  tungsten: Option[Tungsten] = None,
  aluminum: Option[Aluminum] = None,
  titanium: Option[Titanium] = None,
  aggricultureSupplies: Option[AggricultureSupplies] = None,
  quartz: Option[Quartz] = None,
  corundum: Option[Corundum] = None,
  diamond: Option[Diamond] = None,
  beryl: Option[Beryl] = None,
  laranite: Option[Laranite] = None,
  processedFood: Option[ProcessedFood] = None,
  waste: Option[Waste] = None,
  stims: Option[Stims] = None,
  distilledSpirits: Option[DistilledSpirits] = None,
  medicalSupplies: Option[MedicalSupplies] = None,
  scrap: Option[Scrap] = None,
  altruciatoxin: Option[Altruciatoxin] = None,
  wiDoW: Option[WiDoW] = None,
) {
  def profitFromOptions[T <: Material](buy: Option[T], sell: Option[T]): Option[Float] = {
    buy.flatMap{ b =>
      sell.map(_._sellPrice - b._buyPrice)
    }
  }

  def bestProfit(o: Base, ship: Ship): (Material, Float) = {
    profitFromOptions(astatine, o.astatine)
  }
}

case object PortOlisar extends Base(
  astatine = Some(Astatine(0, 8.25)),
  hydrogen = Some(Hydrogen(0, 0.17)),
  fluorine = Some(Fluorine(2.65, 0)),
  iodine = Some(Iodine(0, 0.44)),
  chlorine = Some(Chlorine(0, 1.55)),
  agricium = Some(Agricium(0, 25.72)),
  gold = Some(Gold(6.05, 0)),
  tungsten = Some(Tungsten(0, 3.94)),
  aluminum = Some(Aluminum(0, 1.22)),
  titanium = Some(Titanium(0, 2.29)),
  aggricultureSupplies = Some(AggricultureSupplies(0.75, 0)),
  quartz = Some(Quartz(0, 1.46)),
  corundum = Some(Corundum(0, 2.58)),
  diamond = Some(Diamond(0, 6.8)),
  beryl = Some(Beryl(0, 4.3)),
  laranite = Some(Laranite(0, 28.54)),
  processedFood = Some(ProcessedFood(0, 1.38)),
  waste = Some(Waste(0.45, 0)),
  stims = Some(Stims(0, 3.41)),
  distilledSpirits = Some(DistilledSpirits(0, 4.95)),
  medicalSupplies = Some(MedicalSupplies(17.02, 0)),
  scrap = Some(Scrap(1.52, 0)),
)
case object ArcCorpMiningArea141 extends Base(
  agricium = Some(Agricium(24.27, 0)),
  tungsten = Some(Tungsten(3.65, 0)),
  quartz = Some(Quartz(1.33, 0)),
  beryl = Some(Beryl(4.09, 0)),
  processedFood = Some(ProcessedFood(0, 1.38)),
  stims = Some(Stims(0, 3.42)),
  distilledSpirits = Some(DistilledSpirits(0, 4.95)),
  medicalSupplies = Some(MedicalSupplies(0, 17.97)),
  altruciatoxin = Some(Altruciatoxin(0, 11.8)),
  wiDoW = Some(WiDoW(0, 27)),
)
case object BountyfulHarvestHydroponics extends Base(
  aggricultureSupplies = Some(AggricultureSupplies(0, 0.8)),
  processedFood = Some(ProcessedFood(1.31, 0)),
  stims = Some(Stims(3.17, 0)),
  distilledSpirits = Some(DistilledSpirits(4.64, 0)),
  medicalSupplies = Some(MedicalSupplies(0, 17.97)),
)
case object ShubinMiningFacility extends Base(
  gold = Some(Gold(5.71, 0)),
  tungsten = Some(Tungsten(3.65, 0)),
  quartz = Some(Quartz(1.33, 0)),
  beryl = Some(Beryl(4.09, 0)),
  processedFood = Some(ProcessedFood(0, 1.38)),
  stims = Some(Stims(0, 3.42)),
  distilledSpirits = Some(DistilledSpirits(0, 4.95)),
  medicalSupplies = Some(MedicalSupplies(0, 17.97)),
  altruciatoxin = Some(Altruciatoxin(0, 11.8)),
  wiDoW = Some(WiDoW(0, 27)),
)
case object KudreOre extends Base(
  agricium = Some(Agricium(24.27, 0)),
  gold = Some(Gold(5.71, 0)),
  tungsten = Some(Tungsten(3.65, 0)),
  quartz = Some(Quartz(1.33, 0)),
  beryl = Some(Beryl(4.09, 0)),
  processedFood = Some(ProcessedFood(0, 1.38)),
  stims = Some(Stims(0, 3.42)),
  distilledSpirits = Some(DistilledSpirits(0, 4.95)),
  medicalSupplies = Some(MedicalSupplies(0, 17.97)),
  altruciatoxin = Some(Altruciatoxin(0, 11.8)),
  wiDoW = Some(WiDoW(0, 27)),
)
case object TerraMillsHydroFarm extends Base(
  aggricultureSupplies = Some(AggricultureSupplies(0, 0.8)),
  processedFood = Some(ProcessedFood(1.31, 0)),
  stims = Some(Stims(3.17, 0)),
  distilledSpirits = Some(DistilledSpirits(4.64, 0)),
  medicalSupplies = Some(MedicalSupplies(0, 17.97)),
)
case object GaletteFamilyFarms extends Base(
  aggricultureSupplies = Some(AggricultureSupplies(0, 0.8)),
  processedFood = Some(ProcessedFood(1.31, 0)),
  stims = Some(Stims(3.17, 0)),
  distilledSpirits = Some(DistilledSpirits(4.64, 0)),
  medicalSupplies = Some(MedicalSupplies(0, 17.97)),
)
case object HickesResearchOutpost extends Base(
  astatine = Some(Astatine(0, 8.25)),
  fluorine = Some(Fluorine(0, 2.75)),
  iodine = Some(Iodine(0, 0.44)),
  chlorine = Some(Chlorine(0, 1.55)),
  aggricultureSupplies = Some(AggricultureSupplies(0.69, 0)),
  processedFood = Some(ProcessedFood(0, 1.38)),
)
case object TramMyersMining extends Base(
  agricium = Some(Agricium(25.72, 0)),
  aluminum = Some(Aluminum(1.17, 0)),
  titanium = Some(Titanium(2.1, 0)),
  corundum = Some(Corundum(2.41, 0)),
  diamond = Some(Diamond(6.39, 0)),
  laranite = Some(Laranite(27.45, 0)),
  processedFood = Some(ProcessedFood(0, 1.38)),
  stims = Some(Stims(0, 3.42)),
  distilledSpirits = Some(DistilledSpirits(0, 4.95)),
  medicalSupplies = Some(MedicalSupplies(17.02, 17.97)),
  altruciatoxin = Some(Altruciatoxin(0, 11.8)),
  wiDoW = Some(WiDoW(0, 27)),
)
case object GrimHex extends Base(
  astatine = Some(Astatine(0, 8.25)),
  hydrogen = Some(Hydrogen(0, 0.17)),
  fluorine = Some(Fluorine(0, 2.75)),
  iodine = Some(Iodine(0, 0.44)),
  chlorine = Some(Chlorine(0, 1.55)),
  gold = Some(Gold(5.96, 0)),
  tungsten = Some(Tungsten(0, 3.95)),
  aluminum = Some(Aluminum(0, 1.22)),
  quartz = Some(Quartz(0, 1.45)),
  diamond = Some(Diamond(6.8, 0)),
  beryl = Some(Beryl(0, 4.3)),
  laranite = Some(Laranite(28.54, 0)),
  processedFood = Some(ProcessedFood(0, 1.38)),
  waste = Some(Waste(0, 0.5)),
  stims = Some(Stims(0, 3.42)),
  distilledSpirits = Some(DistilledSpirits(0, 4.95)),
  medicalSupplies = Some(MedicalSupplies(0, 17.97)),
  scrap = Some(Scrap(1.52, 0)),
  altruciatoxin = Some(Altruciatoxin(0, 11.8)),
  wiDoW = Some(WiDoW(0, 27)),
)
case object ArcCorpMiningArea157 extends Base(
  astatine = Some(Astatine(7.74, 0)),
  hydrogen = Some(Hydrogen(0.12, 0)),
  fluorine = Some(Fluorine(2.54, 0)),
  iodine = Some(Iodine(0.35, 0)),
  chlorine = Some(Chlorine(1.44, 0)),
  processedFood = Some(ProcessedFood(0, 1.38)),
  stims = Some(Stims(0, 3.42)),
  distilledSpirits = Some(DistilledSpirits(0, 4.95)),
  medicalSupplies = Some(MedicalSupplies(0, 17.97)),
  altruciatoxin = Some(Altruciatoxin(0, 11.8)),
  wiDoW = Some(WiDoW(0, 27)),
)
case object BensonMiningOutpost extends Base(
  astatine = Some(Astatine(7.74, 0)),
  hydrogen = Some(Hydrogen(0.12, 0)),
  fluorine = Some(Fluorine(2.54, 0)),
  iodine = Some(Iodine(0.35, 0)),
  chlorine = Some(Chlorine(1.44, 0)),
  processedFood = Some(ProcessedFood(0, 1.38)),
  stims = Some(Stims(0, 3.42)),
  distilledSpirits = Some(DistilledSpirits(0, 4.95)),
  medicalSupplies = Some(MedicalSupplies(0, 17.97)),
  altruciatoxin = Some(Altruciatoxin(0, 11.8)),
  wiDoW = Some(WiDoW(0, 27)),
)
case object DeakingReaserchOutpost extends Base(
  astatine = Some(Astatine(0, 8.25)),
  fluorine = Some(Fluorine(0, 2.75)),
  iodine = Some(Iodine(0, 0.44)),
  chlorine = Some(Chlorine(0, 1.55)),
  aggricultureSupplies = Some(AggricultureSupplies(0.69, 0)),
  processedFood = Some(ProcessedFood(0, 1.38)),
  medicalSupplies = Some(MedicalSupplies(17.02, 0)),
)
case object DrugLab extends Base(
  aggricultureSupplies = Some(AggricultureSupplies(0, 0.8)),
  altruciatoxin = Some(Altruciatoxin(9.79, 0)),
  wiDoW = Some(WiDoW(17, 0)),
)
case object Levski extends Base(
  astatine = Some(Astatine(0, 8.16)),
  hydrogen = Some(Hydrogen(0, 0.17)),
  fluorine = Some(Fluorine(0, 2.75)),
  iodine = Some(Iodine(0.35, 0)),
  chlorine = Some(Chlorine(0, 1.55)),
  agricium = Some(Agricium(0, 25.72)),
  gold = Some(Gold(0, 6.08)),
  tungsten = Some(Tungsten(0, 3.94)),
  aluminum = Some(Aluminum(1.17, 0)),
  titanium = Some(Titanium(0, 2.29)),
  aggricultureSupplies = Some(AggricultureSupplies(0.69, 0)),
  quartz = Some(Quartz(1.33, 0)),
  corundum = Some(Corundum(0, 2.58)),
  diamond = Some(Diamond(0, 6.8)),
  beryl = Some(Beryl(0, 4.3)),
  laranite = Some(Laranite(0, 28.54)),
  processedFood = Some(ProcessedFood(0, 1.38)),
  waste = Some(Waste(0, 0.5)),
  stims = Some(Stims(0, 3.42)),
  distilledSpirits = Some(DistilledSpirits(0, 4.95)),
  medicalSupplies = Some(MedicalSupplies(0, 17.97)),
  scrap = Some(Scrap(0, 1.6)),
  altruciatoxin = Some(Altruciatoxin(0, 11.8)),
  wiDoW = Some(WiDoW(0, 24.2)),
)