sealed class Material(val _buyPrice: Double, val _sellPrice: Double, val _isIllegal: Boolean = false, val _maxStock: Option[Int] = None)

case class Astatine(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Hydrogen(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Fluorine(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Iodine(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Chlorine(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Agricium(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Gold(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Tungsten(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Aluminum(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Titanium(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class AggricultureSupplies(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Quartz(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Corundum(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Diamond(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice, _maxStock = Some(4000))
case class Beryl(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Laranite(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class ProcessedFood(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Waste(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Stims(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class DistilledSpirits(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class MedicalSupplies(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Scrap(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice)
case class Altruciatoxin(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice, _isIllegal = true, _maxStock = Some(5000))
case class WiDoW(buyPrice: Double, sellPrice: Double) extends Material(buyPrice, sellPrice, _isIllegal = true, _maxStock = Some(1000))